# Generated by Django 5.1.1 on 2024-12-07 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
