# Generated by Django 5.1.1 on 2024-12-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_remove_api_content_type_api_api_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_data',
            field=models.TextField(),
        ),
    ]
