# Generated by Django 5.1.1 on 2025-01-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_api_user_table_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='api_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
